import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create schema auth;
create table auth.users(id uuid primary key,email text);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create role anon;create role authenticated;create role service_role bypassrls;
grant usage on schema public,auth to authenticated,anon,service_role;
grant execute on function auth.uid() to authenticated,anon,service_role;`);
await db.exec(await readFile(new URL('../supabase/migrations/001_nexo.sql',import.meta.url),'utf8'));
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
await db.exec(`insert into auth.users values('${id(1)}','admin@example.com'),('${id(2)}','a@example.com'),('${id(3)}','b@example.com'),('${id(4)}','leader@example.com');
insert into clients(id,name) values('${id(10)}','Client A'),('${id(11)}','Client B');
insert into legal_entities(id,client_id,name) values('${id(20)}','${id(10)}','A SA'),('${id(21)}','${id(11)}','B SA');
insert into business_units(id,entity_id,name) values('${id(30)}','${id(20)}','A1'),('${id(31)}','${id(21)}','B1'),('${id(32)}','${id(20)}','A2');
insert into profiles(id,name,email,role,client_id) values('${id(1)}','Admin','admin@example.com','super_admin',null),('${id(2)}','Manager A','a@example.com','gerente','${id(10)}'),('${id(3)}','Manager B','b@example.com','gerente','${id(11)}'),('${id(4)}','Leader A','leader@example.com','lider','${id(10)}');
insert into user_units values('${id(2)}','${id(30)}'),('${id(3)}','${id(31)}'),('${id(4)}','${id(30)}');`);
const as=async n=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);await db.exec('set role authenticated');};
const query=async(sql,args=[])=> (await db.query(sql,args)).rows;
const fail=async(fn,pattern)=>{await assert.rejects(fn,pattern);};
await as(2);
assert.equal((await query('select * from clients')).length,1);
assert.deepEqual((await query('select name from business_units')).map(r=>r.name),['A1']);
assert.equal((await query('select * from profiles')).length,1);
await fail(()=>db.exec(`update profiles set role='super_admin',client_id=null where id='${id(2)}'`),/permission denied/);
await fail(()=>db.exec(`insert into activity(action,record_id) values('Fake','${id(1)}')`),/permission denied/);
await fail(()=>query('select submit_request($1,$2,$3,$4,$5,$6)', ['requerimiento',id(11),id(21),id(31),'Media',{title:'Leak',vacancies:1,required_date:'2026-11-01',details:{description:'Test'}}]),/sin permiso/);
await fail(()=>query('select submit_request($1,$2,$3,$4,$5,$6)', ['requerimiento',id(10),id(20),id(32),'Media',{title:'Hidden unit',vacancies:1,required_date:'2026-11-01',details:{description:'Test'}}]),/sin permiso/);
const r=(await query('select submit_request($1,$2,$3,$4,$5,$6) as id',['requerimiento',id(10),id(20),id(30),'Alta',{title:'Operario A',vacancies:1,required_date:'2026-11-01',details:{description:'Operator'}}]))[0].id;
await fail(()=>query('select review_request($1,true,\'\')',[r]),/Acceso denegado/);
await as(1);await query("select review_request($1,true,'')",[r]);
assert.equal((await query('select * from requirements')).length,1);
assert.equal((await query('select * from searches')).length,1);
await fail(()=>query("select review_request($1,true,'')",[r]),/ya fue revisada/);
const sA=(await query('select id from searches'))[0].id;
const candidate=(await query('select save_candidate($1,$2,null) as id',[{name:'Unique person',dni:'99123456'},sA]))[0].id;
await fail(()=>query('select save_candidate($1,$2,null)',[{name:'Duplicate',dni:'99.123.456'},sA]),/Candidato existente/);
const appA=(await query('select id from applications'))[0].id;
await query("select move_application($1,'Ingresado','Confirmed')",[appA]);
const second=(await query('select save_candidate($1,$2,null) as id',[{name:'Second person',dni:'99123457'},sA]))[0].id;
const appSecond=(await query('select id from applications where candidate_id=$1',[second]))[0].id;
await fail(()=>query("select move_application($1,'Ingresado','Over capacity')",[appSecond]),/vacantes ya fueron cubiertas/);
await as(3);
assert.equal((await query('select * from candidates')).length,0);
assert.equal((await query('select * from searches')).length,0);
const rb=(await query('select submit_request($1,$2,$3,$4,$5,$6) as id',['requerimiento',id(11),id(21),id(31),'Media',{title:'Operario B',vacancies:1,required_date:'2026-11-01',details:{description:'Operator B'}}]))[0].id;
await as(1);await query("select review_request($1,true,'')",[rb]);
const sB=(await query('select id from searches where unit_id=$1',[id(31)]))[0].id;
await query('select save_candidate($1,$2,$3)',[{},sB,candidate]);
await as(3);
assert.equal((await query('select * from candidates')).length,1);
assert.equal((await query('select * from applications')).length,1);
assert.equal((await query('select * from stage_history')).length,1);
assert.equal((await query('select new_stage from stage_history'))[0].new_stage,'Postulado');
assert.equal((await query('select * from notifications')).length,1);
await fail(()=>query('select finalize_user_request($1,$2)',[r,id(3)]),/permission denied/);
await as(2);
const unitRequest=(await query('select submit_request($1,$2,$3,$4,$5,$6) as id',['unidad',id(10),id(20),null,'Media',{name:'New A3',location:'BA',responsible:'A'}]))[0].id;
await as(1);await fail(()=>query("select review_request($1,false,'')",[unitRequest]),/motivo/);
await query("select review_request($1,true,'')",[unitRequest]);
await as(2);assert.equal((await query('select * from business_units')).length,2);
await as(4);await fail(()=>query('select submit_request($1,$2,$3,$4,$5,$6)',['unidad',id(10),id(20),null,'Media',{name:'Unauthorized',location:'BA'}]),/Solo un gerente/);
await as(1);await fail(()=>query('select set_user_permissions($1,$2,$3,$4)',[id(2),'gerente',[id(31)],true]),/otro cliente/);
await query('select set_user_permissions($1,$2,$3,$4)',[id(2),'gerente',[id(30)],false]);
await as(2);assert.equal((await query('select * from business_units')).length,0);assert.equal((await query('select * from candidates')).length,0);
await db.exec('reset role;set role anon');
await fail(()=>query('select * from candidates'),/permission denied/);
await fail(()=>query("select is_admin()"),/permission denied/);
await db.close();
console.log('PASS: migration, cross-client/unit isolation, role escalation, audit protection, atomic approvals, candidate uniqueness, history isolation, capacity, invitation restrictions, inactive and anonymous access.');
