import {useEffect,useMemo,useRef,useState,FormEvent,ReactNode} from 'react';
import {LayoutDashboard,Inbox,Building2,Layers,MapPin,Users,ClipboardList,BriefcaseBusiness,UserRound,ChartNoAxesCombined,Activity,Settings,Search as SearchIcon,Bell,Plus,ChevronDown,X,Check,ArrowUpRight,LogOut,Menu,CalendarDays,Clock,Target,CheckCircle2,ShieldCheck,Download,ChevronRight,Mail,RefreshCw} from 'lucide-react';
import {Candidate,Data,Profile,Request,Search,age,emptyData,now,outcomes,roleNames,scopeData,stages,uid} from './model';
import {makeDemo} from './demo';
import {configured,supabase} from './supabase';
import {insertRow,loadData,logDemo,reviewDemo,rpc} from './repository';

type Modal={type:string;record?:any}|null;
type Field={key:string;label:string;type?:string;options?:{value:string;label:string}[];required?:boolean;min?:number;max?:string;wide?:boolean};
const date=(v:string)=>new Date(v).toLocaleDateString('es-AR',{day:'2-digit',month:'short',year:'numeric'});
const datetime=(v:string)=>new Date(v).toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'});
const options=(items:any[],label='name')=>items.map(i=>({value:i.id,label:i[label]}));
const initial=(name:string)=>name.split(' ').slice(0,2).map(n=>n[0]).join('');
const nav=[['Dashboard',LayoutDashboard],['Solicitudes',Inbox],['Clientes',Building2],['Razones sociales',Layers],['Unidades',MapPin],['Usuarios',Users],['Requerimientos',ClipboardList],['Búsquedas',BriefcaseBusiness],['Candidatos',UserRound],['Reportes',ChartNoAxesCombined],['Actividad',Activity],['Configuración',Settings]] as const;
function Badge({children}:{children:ReactNode}) {const t=String(children);const cls=/Aprobad|Ingresad|Cubiert|Activo|Realizada/.test(t)?'green':/Rechaz|Cancelad|No seleccion|Desist/.test(t)?'red':/Pendiente|feedback|Alta/.test(t)?'amber':'purple';return <span className={`badge ${cls}`}><i/>{children}</span>}
function Avatar({name}:{name:string}){return <span className="avatar" aria-hidden="true">{initial(name)}</span>}
function Empty({text='Todavía no hay registros para esta selección.'}:{text?:string}) {return <div className="empty"><Inbox size={28}/><strong>Sin resultados</strong><p>{text}</p></div>}
function Form({fields,initialValues={},submitLabel='Guardar',onSubmit,busy}:{fields:Field[];initialValues?:Record<string,any>;submitLabel?:string;onSubmit:(v:Record<string,string>)=>Promise<void>;busy:boolean}) {
 const [values,setValues]=useState<Record<string,string>>(Object.fromEntries(fields.map(f=>[f.key,String(initialValues[f.key]??'')])));
 return <form onSubmit={e=>{e.preventDefault();void onSubmit(values)}}><div className="form-grid">{fields.map(f=><label key={f.key} className={f.wide?'wide':''}>{f.label}{f.required&&<span className="required"> *</span>}{f.type==='textarea'?<textarea value={values[f.key]} required={f.required} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>:f.options?<select value={values[f.key]} required={f.required} onChange={e=>setValues({...values,[f.key]:e.target.value})}><option value="">Seleccionar</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input type={f.type||'text'} value={values[f.key]} required={f.required} min={f.min} max={f.max} step={f.type==='number'?1:undefined} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>}</label>)}</div><div className="form-footer"><span>Los campos con * son obligatorios.</span><button className="primary" disabled={busy}>{busy?'Guardando…':submitLabel}</button></div></form>
}
function ModalShell({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}) {
 const ref=useRef<HTMLDivElement>(null);const closeRef=useRef(onClose);closeRef.current=onClose;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const box=ref.current;box?.querySelector<HTMLElement>('input,select,button,textarea')?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')closeRef.current();if(e.key==='Tab'&&box){const els=[...box.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,a[href]')];const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handler);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handler);document.body.style.overflow=old;previous?.focus();}},[]);
 return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div ref={ref} className="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><header><div><span className="eyebrow">NEXO · PORTAL DE SELECCIÓN</span><h2 id="dialog-title">{title}</h2></div><button className="icon-btn" onClick={onClose} aria-label="Cerrar"><X/></button></header><div className="modal-body">{children}</div></div></div>
}

export default function App() {
 const [data,setData]=useState<Data>(emptyData);const [user,setUser]=useState<Profile|null>(null);const [demo,setDemo]=useState(false);const [loading,setLoading]=useState(configured);const [busy,setBusy]=useState(false);const [page,setPage]=useState('Dashboard');const [query,setQuery]=useState('');const [global,setGlobal]=useState('');const [filter,setFilter]=useState('');const [clientFilter,setClientFilter]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [modal,setModal]=useState<Modal>(null);const [message,setMessage]=useState('');const [error,setError]=useState('');const [mobile,setMobile]=useState(false);const [notifications,setNotifications]=useState(false);const [recovery,setRecovery]=useState(new URLSearchParams(window.location.search).get('setup')==='1');const [activeSearch,setActiveSearch]=useState<string|null>(null);const [loginEmail,setLoginEmail]=useState('');const [loginPassword,setLoginPassword]=useState('');
 const admin=user?.role==='super_admin';const scoped=useMemo(()=>user?scopeData(data,user):emptyData,[data,user]);
 const refresh=async()=>{const d=await loadData();setData(d);return d;};
 useEffect(()=>{if(!supabase)return;let alive=true;const initialize=async()=>{try{const {data:{session}}=await supabase!.auth.getSession();if(session){const d=await loadData();const p=d.profiles.find(p=>p.id===session.user.id&&p.active);if(!p)throw new Error('Tu acceso todavía no fue aprobado. Contactá a NEXO.');if(alive){setData(d);setUser(p);}}}catch(e:any){if(alive)setError(e.message)}finally{if(alive)setLoading(false)}};void initialize();const {data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){setRecovery(true);setLoading(false)}if(event==='SIGNED_OUT'){setUser(null);setData(emptyData)}if((event==='SIGNED_IN'||event==='USER_UPDATED')&&session){setTimeout(()=>{if(alive)void initialize()},0)}});return()=>{alive=false;subscription.unsubscribe()}},[]);
 useEffect(()=>{if(!user||demo||!supabase)return;const channel=supabase.channel('nexo-notifications-'+user.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`user_id=eq.${user.id}`},payload=>{setData(d=>({...d,notifications:[payload.new as any,...d.notifications]}));setMessage('Recibiste una nueva notificación.')}).subscribe();return()=>{void supabase!.removeChannel(channel)}},[user?.id,demo]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),5000);return()=>clearTimeout(t)},[message]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool||!user)return;const life=new AbortController();try{Promise.resolve(ctx.registerTool({name:'search_nexo',title:'Buscar en NEXO',description:'Busca candidatos y búsquedas visibles para el usuario actual.',inputSchema:{type:'object',properties:{query:{type:'string',minLength:1}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(!input||typeof input.query!=='string'||!input.query.trim())throw new Error('La búsqueda no puede estar vacía.');const q=input.query.toLowerCase();setGlobal(input.query);return {candidates:scoped.candidates.filter(c=>(c.name+' '+c.dni+' '+c.cuil).toLowerCase().includes(q)).slice(0,10).map(c=>({id:c.id,name:c.name})),searches:scoped.searches.filter(s=>s.title.toLowerCase().includes(q)).slice(0,10).map(s=>({id:s.id,title:s.title}))}}},{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[user?.id,scoped]);
 useEffect(()=>{if(!user)return;const params=new URLSearchParams(window.location.search);const id=params.get('request');if(!id)return;const r=scoped.requests.find(r=>r.id===id);if(r){setPage('Solicitudes');setModal({type:'review',record:r});}else setError('La solicitud no está disponible o no tenés permiso para verla.');params.delete('request');window.history.replaceState({},'',window.location.pathname+(params.toString()?'?'+params.toString():''));},[user?.id,scoped.requests]);
 const run=async(action:()=>Promise<void>,success='Cambios guardados correctamente.')=>{setBusy(true);setError('');try{await action();setMessage(success);setModal(null)}catch(e:any){setError(e.message||'No se pudo completar la acción.')}finally{setBusy(false)}};
 const mutate=async(fn:(d:Data)=>void)=>{const d=structuredClone(data);fn(d);setData(d);if(demo)sessionStorage.setItem('nexo-demo',JSON.stringify(d));};
 const save=async(key:keyof Data,row:any,action:string,unit:string|null=null)=>{if(demo)await mutate(d=>{(d[key] as any[]).push(row);logDemo(d,user!,action,row.id,unit)});else{await insertRow(key,row);await refresh()}};
 const navigate=(p:string)=>{setPage(p);setQuery('');setFilter('');setClientFilter('');setActiveSearch(null);setMobile(false);setGlobal('');};
 const clientName=(id:string)=>scoped.clients.find(c=>c.id===id)?.name||'Cliente';
 const entityFor=(unit:string)=>scoped.entities.find(e=>e.id===scoped.units.find(u=>u.id===unit)?.entity_id);
 const unitName=(id:string)=>scoped.units.find(u=>u.id===id)?.name||'Sin unidad';
 const clientFor=(unit:string)=>clientName(entityFor(unit)?.client_id||'');
 const match=(text:string)=>text.toLowerCase().includes(query.toLowerCase());
 const range=(d:string)=>(!from||d.slice(0,10)>=from)&&(!to||d.slice(0,10)<=to);
 const pending=scoped.requests.filter(r=>r.status==='Pendiente').length;
 const unread=scoped.notifications.filter(n=>!n.read&&n.user_id===user?.id).length;
 const selectedSearch=scoped.searches.find(s=>s.id===activeSearch);
 const openSearch=(s:Search)=>{setPage('Búsquedas');setActiveSearch(s.id);setGlobal('')};

 const startDemo=()=>{let d:Data;try{d=JSON.parse(sessionStorage.getItem('nexo-demo')||'null')||makeDemo()}catch{d=makeDemo()}setData(d);setUser(d.profiles[0]);setDemo(true);setLoading(false);setError('');setPage('Dashboard')};
 const login=async(e:FormEvent)=>{e.preventDefault();if(!supabase){setError('La conexión real todavía no está configurada. Podés explorar la demostración.');return}await run(async()=>{const {data:{user:u},error}=await supabase!.auth.signInWithPassword({email:loginEmail,password:loginPassword});if(error)throw error;const d=await refresh();const p=d.profiles.find(p=>p.id===u?.id&&p.active);if(!p){await supabase!.auth.signOut();throw new Error('Tu acceso todavía no fue aprobado.')}setUser(p);setDemo(false)},'Bienvenido a NEXO.')};
 const logout=async()=>{if(!demo&&supabase)await supabase!.auth.signOut();setUser(null);setDemo(false);setData(emptyData);setLoginPassword('')};
 const approve=async(r:Request,yes:boolean,reason:string)=>{if(demo)await mutate(d=>reviewDemo(d,user!,d.requests.find(x=>x.id===r.id)!,yes,reason));else{if(r.type==='usuario'&&yes){const {data:result,error}=await supabase!.functions.invoke('invite-user',{body:{request_id:r.id,redirect_to:window.location.origin}});if(error)throw error;if(result?.error)throw new Error(result.error)}else await rpc('review_request',{p_request_id:r.id,p_approve:yes,p_reason:reason});await refresh()}};
 const move=async(appId:string,stage:string,note:string)=>{if(!admin)throw new Error('Solo la selectora puede cambiar el estado.');if(demo)await mutate(d=>{const a=d.applications.find(a=>a.id===appId)!;const search=d.searches.find(s=>s.id===a.search_id)!;if(['Cubierta','Cancelada'].includes(search.status))throw new Error('La búsqueda está cerrada.');if(a.stage===stage)throw new Error('El candidato ya está en esta etapa.');if(stage==='Ingresado'&&d.applications.filter(x=>x.search_id===search.id&&x.stage==='Ingresado').length>=search.vacancies)throw new Error('Todas las vacantes ya fueron cubiertas.');d.history.unshift({id:uid(),application_id:a.id,actor_id:user!.id,old_stage:a.stage,new_stage:stage,note,created_at:now()});a.stage=stage;logDemo(d,user!,'Cambió el estado de un candidato a '+stage,a.id,d.searches.find(s=>s.id===a.search_id)!.unit_id)});else{await rpc('move_application',{p_application_id:appId,p_stage:stage,p_note:note});await refresh()}};

 if(loading)return <div className="loading"><div className="brand-symbol">N</div><h2>Cargando NEXO…</h2></div>;
 if(recovery)return <div className="login-page"><div className="login-card"><div className="wordmark">NEXO<span>PORTAL DE SELECCIÓN</span></div><h2>Elegí tu nueva contraseña</h2>{error&&<div className="error" role="alert">{error}</div>}<Form fields={[{key:'password',label:'Nueva contraseña',type:'password',required:true}]} busy={busy} submitLabel="Actualizar contraseña" onSubmit={async v=>run(async()=>{if(v.password.length<10)throw new Error('Usá al menos 10 caracteres.');const {error}=await supabase!.auth.updateUser({password:v.password});if(error)throw error;setRecovery(false);window.history.replaceState({},'',window.location.pathname)},'Contraseña actualizada.')}/></div></div>;
 if(!user)return <div className="login-page"><div className="login-intro"><div className="wordmark">NEXO<span>PORTAL DE SELECCIÓN</span></div><span className="eyebrow">PERSONAS. EQUIPOS. OPORTUNIDADES.</span><h1>El próximo gran<br/>equipo empieza<br/><em>con una conexión.</em></h1><p>Conectamos talento con oportunidades.</p><div className="login-proof"><ShieldCheck size={20}/><span>Un espacio privado para cada empresa.</span></div></div><div className="login-card"><span className="eyebrow">BIENVENIDO A NEXO</span><h2>Ingresar al portal</h2><p>Gestioná tus procesos de selección en un solo lugar.</p>{error&&<div className="error" role="alert">{error}</div>}<form onSubmit={login}><label>Email corporativo<input type="email" autoComplete="username" required value={loginEmail} onChange={e=>setLoginEmail(e.target.value)} placeholder="nombre@empresa.com"/></label><label>Contraseña<input type="password" autoComplete="current-password" required value={loginPassword} onChange={e=>setLoginPassword(e.target.value)} placeholder="Tu contraseña"/></label><button type="button" className="text-btn forgot" disabled={busy} onClick={()=>run(async()=>{if(!supabase)throw new Error('Primero configurá Supabase.');if(!loginEmail)throw new Error('Escribí tu email corporativo.');const {error}=await supabase.auth.resetPasswordForEmail(loginEmail,{redirectTo:window.location.origin});if(error)throw error},'Si tu cuenta existe, recibirás un enlace para recuperar el acceso.')}>¿Olvidaste tu contraseña?</button><button className="primary full" disabled={busy}>{busy?'Ingresando…':'Ingresar'}</button></form><div className="demo-login"><span>¿Querés conocer el portal?</span><button className="secondary full" onClick={startDemo}>Explorar demostración</button><small>Datos ficticios. Sin conexión a la base real.</small></div><div className="login-bottom">Acceso por invitación · Sin registro público</div></div>{message&&<div className="toast" role="status"><CheckCircle2 size={18}/>{message}</div>}</div>;

 const filteredSearches=scoped.searches.filter(s=>match(s.title+' '+clientFor(s.unit_id))&&(!filter||s.status===filter)&&(!clientFilter||entityFor(s.unit_id)?.client_id===clientFilter)&&range(s.created_at));
 const reportReq=scoped.requirements.filter(r=>(!clientFilter||r.client_id===clientFilter)&&range(r.created_at));
 const reportSearch=scoped.searches.filter(s=>(!clientFilter||entityFor(s.unit_id)?.client_id===clientFilter)&&range(s.created_at));
 const reportApp=scoped.applications.filter(a=>reportSearch.some(s=>s.id===a.search_id));
 const reportInterviews=scoped.interviews.filter(i=>reportApp.some(a=>a.id===i.application_id)&&range(i.date));
 const covered=reportApp.filter(a=>a.stage==='Ingresado').length;
 const vacancies=reportReq.reduce((n,r)=>n+r.vacancies,0);
 const closedSearches=reportSearch.filter(s=>s.closed_at);
 const average=closedSearches.length?(closedSearches.reduce((n,s)=>n+(new Date(s.closed_at!).getTime()-new Date(s.created_at).getTime())/86400000,0)/closedSearches.length).toLocaleString('es-AR',{maximumFractionDigits:1}):'—';
 const summary=[{label:'Búsquedas abiertas',value:scoped.searches.filter(s=>!['Cubierta','Cancelada'].includes(s.status)).length,icon:BriefcaseBusiness,help:'Procesos en curso',color:'purple'},{label:'Requerimientos del mes',value:scoped.requirements.filter(r=>r.created_at.slice(0,7)===now().slice(0,7)).length,icon:ClipboardList,help:'Solicitudes aprobadas',color:'blue'},{label:'Candidatos activos',value:new Set(scoped.applications.filter(a=>!['Ingresado',...outcomes].includes(a.stage)).map(a=>a.candidate_id)).size,icon:Users,help:'En procesos de selección',color:'purple'},{label:'Entrevistas del mes',value:scoped.interviews.filter(i=>i.date.slice(0,7)===now().slice(0,7)).length,icon:CalendarDays,help:'Entrevistas registradas',color:'amber'},{label:'Ingresos del mes',value:new Set(scoped.history.filter(h=>h.new_stage==='Ingresado'&&h.created_at.slice(0,7)===now().slice(0,7)).map(h=>h.application_id)).size,icon:CheckCircle2,help:'Talento incorporado',color:'green'},{label:'Tiempo de cobertura',value:average,icon:Clock,help:'Días · búsquedas cerradas',color:'blue'}];
 const primaryAction=page==='Clientes'?{label:'Nuevo cliente',type:'client'}:page==='Razones sociales'?{label:'Nueva razón social',type:'entity'}:page==='Unidades'?{label:admin?'Nueva unidad':'Solicitar unidad',type:admin?'unit':'request-unit'}:page==='Usuarios'?{label:'Solicitar alta de usuario',type:'request-user'}:page==='Candidatos'?{label:'Nuevo candidato',type:'candidate'}:{label:'Nuevo requerimiento',type:'requirement'};
 const actionAllowed=admin||['Dashboard','Requerimientos','Unidades','Solicitudes','Usuarios'].includes(page)&&user.role==='gerente';
 const globalResults=global.trim()?{candidates:scoped.candidates.filter(c=>(c.name+' '+c.dni+' '+c.cuil+' '+c.email+' '+c.phone).toLowerCase().replaceAll('.','').includes(global.toLowerCase().replaceAll('.',''))).slice(0,5),searches:scoped.searches.filter(s=>(s.title+' '+s.id).toLowerCase().includes(global.toLowerCase())).slice(0,4),clients:scoped.clients.filter(c=>c.name.toLowerCase().includes(global.toLowerCase())).slice(0,3),requirements:scoped.requirements.filter(r=>(r.title+' '+r.id).toLowerCase().includes(global.toLowerCase())).slice(0,3),users:scoped.profiles.filter(p=>(p.name+' '+p.email).toLowerCase().includes(global.toLowerCase())).slice(0,3)}:null;
 const toolbar=(statuses:string[]=[],client=false)=><div className="toolbar"><div className="input-search"><SearchIcon size={17}/><input aria-label="Buscar en esta sección" placeholder="Buscar en esta sección…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{statuses.length>0&&<select aria-label="Filtrar estado" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos los estados</option>{statuses.map(s=><option key={s}>{s}</option>)}</select>}{client&&<select aria-label="Filtrar cliente" value={clientFilter} onChange={e=>setClientFilter(e.target.value)}><option value="">Todos los clientes</option>{scoped.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}</div>;
 const searchTable=(items:Search[],compact=false)=><div className="table-wrap"><table><thead><tr><th>PUESTO / BÚSQUEDA</th><th>CLIENTE / UNIDAD</th><th>VACANTES</th><th>ESTADO</th>{!compact&&<th>ENTREVISTAS</th>}<th>APERTURA</th><th/></tr></thead><tbody>{items.map(s=>{const count=scoped.interviews.filter(i=>i.result==='Realizada'&&scoped.applications.some(a=>a.id===i.application_id&&a.search_id===s.id)).length;return <tr key={s.id}><td><button className="row-link" onClick={()=>openSearch(s)}>{s.title}</button><small>NX-{s.id.slice(-5).toUpperCase()}</small></td><td><span>{clientFor(s.unit_id)}</span><small>{unitName(s.unit_id)}</small></td><td><span className="vacancy"><Users size={14}/>{s.vacancies}</span></td><td><Badge>{s.status}</Badge></td>{!compact&&<td><span>{count} / {s.interview_goal}</span><div className="tiny-progress"><i style={{width:`${Math.min(count/s.interview_goal*100,100)}%`}}/></div></td>}<td>{date(s.created_at)}</td><td><button className="icon-btn" aria-label={'Abrir '+s.title} onClick={()=>openSearch(s)}><ChevronRight size={18}/></button></td></tr>})}</tbody></table>{!items.length&&<Empty/>}</div>;

 return <div className="app"><aside className={mobile?'sidebar mobile-open':'sidebar'}><div className="sidebar-brand"><div className="brand-symbol">N</div><div className="wordmark">NEXO<span>PORTAL DE SELECCIÓN</span></div><button className="mobile-close icon-btn" onClick={()=>setMobile(false)} aria-label="Cerrar menú"><X/></button></div><div className="workspace-label">ESPACIO DE TRABAJO</div><nav>{nav.filter(([p])=>admin||!['Usuarios','Configuración'].includes(p)).map(([p,Icon])=><button key={p} className={page===p?'nav-item active':'nav-item'} onClick={()=>navigate(p)}><Icon size={19}/><span>{!admin&&p==='Solicitudes'?'Mis solicitudes':!admin&&p==='Búsquedas'?'Mis búsquedas':p}</span>{p==='Solicitudes'&&pending>0&&<b>{pending}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="private-label"><ShieldCheck size={16}/><span>Portal privado</span></div><div className="sidebar-user"><Avatar name={user.name}/><div><strong>{user.name}</strong><small>{roleNames[user.role]}</small></div><button className="icon-btn" onClick={logout} aria-label="Cerrar sesión"><LogOut size={17}/></button></div></div></aside>{mobile&&<div className="mobile-scrim" onClick={()=>setMobile(false)}/>}
 <div className="app-body"><header className="topbar"><button className="mobile-toggle icon-btn" onClick={()=>setMobile(true)} aria-label="Abrir menú"><Menu/></button><div className="breadcrumb">Portal de Selección <ChevronRight size={14}/><strong>{page}</strong></div><div className="global-search"><SearchIcon size={17}/><input aria-label="Buscar globalmente" value={global} placeholder="Buscar personas, búsquedas, empresas…" onChange={e=>setGlobal(e.target.value)}/><kbd>⌕</kbd>{globalResults&&<div className="search-results">{globalResults.candidates.map(c=><button key={c.id} onClick={()=>{setModal({type:'candidate-detail',record:c});setGlobal('')}}><UserRound size={17}/><span>{c.name}<small>Candidato · DNI {c.dni||'Sin DNI'}</small></span></button>)}{globalResults.searches.map(s=><button key={s.id} onClick={()=>openSearch(s)}><BriefcaseBusiness size={17}/><span>{s.title}<small>Búsqueda</small></span></button>)}{globalResults.clients.map(c=><button key={c.id} onClick={()=>{navigate('Clientes');setQuery(c.name)}}><Building2 size={17}/><span>{c.name}<small>Cliente</small></span></button>)}{globalResults.requirements.map(r=><button key={r.id} onClick={()=>{navigate('Requerimientos');setQuery(r.title)}}><ClipboardList size={17}/><span>{r.title}<small>Requerimiento</small></span></button>)}{globalResults.users.map(p=><button key={p.id} onClick={()=>{setGlobal('');setModal({type:'profile',record:p})}}><Users size={17}/><span>{p.name}<small>Usuario</small></span></button>)}{Object.values(globalResults).every(a=>!a.length)&&<p>Sin coincidencias.</p>}</div>}</div><div className="top-actions"><button className="notification-btn icon-btn" aria-label={`Notificaciones, ${unread} sin leer`} onClick={()=>setNotifications(!notifications)}><Bell size={21}/>{unread>0&&<i>{unread}</i>}</button><div className="divider"/><Avatar name={user.name}/></div></header>
 {demo&&<div className="demo-strip"><span><i/>Demostración · Datos ficticios, cambios guardados solo en esta pestaña</span><label>Vista de<select aria-label="Cambiar usuario de demostración" value={user.id} onChange={e=>{setUser(data.profiles.find(p=>p.id===e.target.value)!);navigate('Dashboard')}}>{data.profiles.map(p=><option key={p.id} value={p.id}>{p.name} · {roleNames[p.role]}</option>)}</select></label></div>}
 {notifications&&<div className="notifications-panel"><header><h3>Notificaciones <span>{unread}</span></h3><button className="icon-btn" aria-label="Cerrar notificaciones" onClick={()=>setNotifications(false)}><X size={18}/></button></header>{scoped.notifications.filter(n=>n.user_id===user.id).sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,20).map(n=><button key={n.id} className={n.read?'notice':'notice unread'} onClick={()=>{void run(async()=>{if(demo)await mutate(d=>{d.notifications.find(x=>x.id===n.id)!.read=true});else{const {error}=await supabase!.from('notifications').update({read:true}).eq('id',n.id);if(error)throw error;await refresh()}if(n.request_id){const r=scoped.requests.find(r=>r.id===n.request_id);if(r)setTimeout(()=>setModal({type:'review',record:r}),0)}setNotifications(false)},'Notificación leída.')}}><Bell size={17}/><div><strong>{n.title}</strong><p>{n.body}</p><small>{datetime(n.created_at)}</small></div></button>)}{!scoped.notifications.length&&<Empty text="No tenés notificaciones."/>}</div>}
 <main><div className="page-heading"><div><span className="eyebrow">{page==='Dashboard'?'TU SELECCIÓN, EN PERSPECTIVA':'GESTIÓN DE TALENTO'}</span><h1>{page==='Dashboard'?`Buen ${new Date().getHours()<13?'día':'día'}, ${user.name.split(' ')[0]}`:page}</h1><p>{page==='Dashboard'?'Una mirada clara a tus procesos y a lo que necesita tu atención.':page==='Solicitudes'?'Revisá, priorizá y resolvé las solicitudes de tu equipo.':page==='Búsquedas'?'Cada oportunidad, desde el primer contacto hasta el ingreso.':page==='Candidatos'?'Una ficha por persona. Todas sus oportunidades e historial.':page==='Reportes'?'Datos reales de los procesos visibles para tu usuario.':'Toda la información de tu espacio, organizada.'}</p></div><div className="heading-actions">{page==='Dashboard'&&<span className="date-chip"><CalendarDays size={16}/>{date(now())}</span>}{actionAllowed&&!['Reportes','Actividad','Configuración'].includes(page)&&<button className="primary" onClick={()=>setModal({type:primaryAction.type})}><Plus size={17}/>{primaryAction.label}</button>}</div></div>
 {error&&<div className="error" role="alert">{error}<button className="icon-btn" aria-label="Cerrar error" onClick={()=>setError('')}><X size={16}/></button></div>}
 {page==='Dashboard'&&<><div className="metrics">{summary.map(m=><div className="metric" key={m.label}><div className="metric-top"><span>{m.label}</span><div className={`metric-icon ${m.color}`}><m.icon size={18}/></div></div><strong>{m.value}</strong><small>{m.help}</small></div>)}</div><div className="dashboard-grid"><section className="panel pending-panel"><div className="panel-heading"><div><h2>Necesitan tu atención <span className="count">{pending}</span></h2><p>Solicitudes pendientes de resolución</p></div><button className="text-btn" onClick={()=>navigate('Solicitudes')}>Ver todas <ChevronRight size={15}/></button></div>{scoped.requests.filter(r=>r.status==='Pendiente').slice(0,3).map(r=><button className="pending-row" key={r.id} onClick={()=>setModal({type:'review',record:r})}><span className={'request-icon '+(r.type==='unidad'?'purple':r.type==='usuario'?'blue':'amber')}>{r.type==='unidad'?<MapPin size={19}/>:r.type==='usuario'?<Users size={19}/>:<ClipboardList size={19}/>}</span><div><strong>{r.type==='unidad'?'Alta de nueva unidad':r.type==='usuario'?'Alta de usuario':'Nuevo requerimiento'}</strong><small>{clientName(r.client_id)} · {r.payload.name||r.payload.title}</small></div><Badge>{r.priority}</Badge><ChevronRight size={16}/></button>)}{!pending&&<Empty text="Todas las solicitudes están al día."/>}</section><section className="panel pipeline-summary"><div className="panel-heading"><div><h2>El talento en movimiento</h2><p>Distribución de candidatos por etapa</p></div><Target size={20}/></div>{['Postulado','Entrevista selectora','Presentado a gerencia','Preingreso'].map((s,i)=>{const n=scoped.applications.filter(a=>a.stage===s).length;return <div className="funnel-row" key={s}><span>{s}</span><div><i style={{width:`${Math.max(n/Math.max(scoped.applications.length,1)*100*3,2)}%`,opacity:1-i*.15}}/></div><strong>{n}</strong></div>})}</section></div><section className="panel"><div className="panel-heading"><div><h2>Búsquedas en curso</h2><p>Las últimas oportunidades de tu equipo</p></div><button className="text-btn" onClick={()=>navigate('Búsquedas')}>Ver búsquedas <ChevronRight size={15}/></button></div>{searchTable(scoped.searches.filter(s=>!['Cubierta','Cancelada'].includes(s.status)).slice(0,5),true)}</section><div className="dashboard-grid bottom-grid"><section className="panel"><div className="panel-heading"><h2>Actividad reciente</h2><button className="text-btn" onClick={()=>navigate('Actividad')}>Ver historial</button></div><ActivityList data={scoped} limit={3}/></section><section className="panel coverage"><span className="eyebrow">RESULTADOS DEL EQUIPO</span><h2>Vacantes cubiertas</h2><strong>{covered}<span> / {vacancies}</span></strong><div className="coverage-bar"><i style={{width:`${Math.min(covered/Math.max(vacancies,1)*100,100)}%`}}/></div><p>{vacancies?Math.round(covered/vacancies*100):0}% de cobertura del período seleccionado</p></section></div></>}
 {page==='Solicitudes'&&<section className="panel">{toolbar(['Pendiente','Aprobada','Rechazada'],true)}<div className="table-wrap"><table><thead><tr><th>SOLICITUD</th><th>CLIENTE / RAZÓN SOCIAL</th><th>SOLICITANTE</th><th>FECHA</th><th>PRIORIDAD</th><th>ESTADO</th><th/></tr></thead><tbody>{scoped.requests.filter(r=>match(r.payload.name+' '+r.payload.title+' '+clientName(r.client_id))&&(!filter||r.status===filter)&&(!clientFilter||r.client_id===clientFilter)).map(r=><tr key={r.id}><td><button className="row-link" onClick={()=>setModal({type:'review',record:r})}>{r.type==='unidad'?'Alta de unidad':r.type==='usuario'?'Alta de usuario':'Nuevo requerimiento'}</button><small>{r.payload.name||r.payload.title}</small></td><td>{clientName(r.client_id)}<small>{scoped.entities.find(e=>e.id===r.entity_id)?.name}</small></td><td>{data.profiles.find(p=>p.id===r.requester_id)?.name||'Usuario solicitante'}</td><td>{date(r.created_at)}</td><td><Badge>{r.priority}</Badge></td><td><Badge>{r.status}</Badge></td><td><button className="secondary small" onClick={()=>setModal({type:'review',record:r})}>{admin&&r.status==='Pendiente'?'Revisar':'Ver detalle'}</button></td></tr>)}</tbody></table>{!scoped.requests.length&&<Empty/>}</div></section>}
 {page==='Clientes'&&<>{toolbar(['Activo','Inactivo'])}<div className="client-grid">{scoped.clients.filter(c=>match(c.name)&&(!filter||c.status===filter)).map(c=><article className="panel client-card" key={c.id}><div className="client-card-top"><span className="client-logo">{initial(c.name)}</span><Badge>{c.status}</Badge></div><h2>{c.name}</h2><p>{c.contact||'Sin contacto'}</p><div className="client-stats"><div><strong>{scoped.entities.filter(e=>e.client_id===c.id).length}</strong><small>Razones sociales</small></div><div><strong>{scoped.units.filter(u=>entityFor(u.id)?.client_id===c.id).length}</strong><small>Unidades</small></div></div><div className="client-card-bottom"><span><Mail size={14}/>{c.email||'Sin email'}</span><button className="icon-btn" aria-label={'Ver '+c.name} onClick={()=>setModal({type:'client-detail',record:c})}><ArrowUpRight size={19}/></button></div></article>)}</div></>}
 {page==='Razones sociales'&&<section className="panel">{toolbar([],true)}<GenericTable headers={['RAZÓN SOCIAL','CLIENTE','CUIT','UNIDADES']} rows={scoped.entities.filter(e=>match(e.name)&&(!clientFilter||e.client_id===clientFilter)).map(e=>[e.name,clientName(e.client_id),e.cuit||'—',scoped.units.filter(u=>u.entity_id===e.id).length])}/></section>}
 {page==='Unidades'&&<section className="panel">{toolbar([],true)}<GenericTable headers={['UNIDAD','RAZÓN SOCIAL','CLIENTE','UBICACIÓN','RESPONSABLE']} rows={scoped.units.filter(u=>match(u.name+' '+u.location)&&(!clientFilter||entityFor(u.id)?.client_id===clientFilter)).map(u=>[u.name,entityFor(u.id)?.name,clientFor(u.id),u.location,u.responsible])}/>{!admin&&user.role==='gerente'&&<div className="panel-footer"><button className="secondary" onClick={()=>setModal({type:'request-user'})}><Plus size={16}/>Solicitar alta de usuario</button></div>}</section>}
 {page==='Usuarios'&&<section className="panel">{toolbar()}<GenericTable headers={['USUARIO','EMAIL','ROL','CLIENTE','ACCESO','']} rows={scoped.profiles.filter(p=>match(p.name+' '+p.email)).map(p=>[<div className="person-cell"><Avatar name={p.name}/><strong>{p.name}</strong></div>,p.email,roleNames[p.role],p.client_id?clientName(p.client_id):'Todos',<Badge>{p.active?'Activo':'Inactivo'}</Badge>,<button className="secondary small" onClick={()=>setModal({type:'permissions',record:p})}>Permisos</button>])}/></section>}
 {page==='Requerimientos'&&<section className="panel">{toolbar(['Pendiente','Aprobado','Rechazado'],true)}<GenericTable headers={['PUESTO','CLIENTE','UNIDAD','VACANTES','PRIORIDAD','ESTADO','FECHA REQUERIDA','']} rows={[...scoped.requirements.map(r=>({...r,pendingRequest:null as Request|null})),...scoped.requests.filter(r=>r.type==='requerimiento'&&r.status==='Pendiente').map(r=>({id:r.id,title:r.payload.title,client_id:r.client_id,unit_id:r.unit_id!,vacancies:r.payload.vacancies,priority:r.priority,status:'Pendiente',required_date:r.payload.required_date,pendingRequest:r}))].filter(r=>match(r.title)&&(!filter||r.status===filter)&&(!clientFilter||r.client_id===clientFilter)).map(r=>[r.title,clientName(r.client_id),unitName(r.unit_id),r.vacancies,<Badge>{r.priority}</Badge>,<Badge>{r.status}</Badge>,r.required_date?date(r.required_date+'T12:00:00'):'—',<button className="text-btn" onClick={()=>{if(r.pendingRequest)setModal({type:'review',record:r.pendingRequest});else{const s=scoped.searches.find(s=>s.requirement_id===r.id);if(s)openSearch(s)}}}>Ver proceso</button>])}/></section>}
 {page==='Búsquedas'&&(selectedSearch?<SearchDetail search={selectedSearch} data={scoped} admin={!!admin} unit={unitName(selectedSearch.unit_id)} client={clientFor(selectedSearch.unit_id)} back={()=>setActiveSearch(null)} onCandidate={c=>setModal({type:'candidate-detail',record:c})} onAdd={()=>setModal({type:'candidate',record:{search_id:selectedSearch.id}})} onMove={a=>setModal({type:'move',record:a})} onInterview={a=>setModal({type:'interview',record:a})} onEdit={()=>setModal({type:'search-edit',record:selectedSearch})}/>:<section className="panel">{toolbar(['En búsqueda','Esperando feedback','Cubierta','Cancelada'],true)}{searchTable(filteredSearches)}</section>)}
 {page==='Candidatos'&&<section className="panel">{toolbar([...stages,...outcomes],true)}<GenericTable headers={['CANDIDATO','DNI / CUIL','LOCALIDAD','EMAIL','PROCESOS','']} rows={scoped.candidates.filter(c=>match(c.name+' '+c.dni+' '+c.cuil+' '+c.email+' '+c.phone)&&(!filter||scoped.applications.some(a=>a.candidate_id===c.id&&a.stage===filter))&&(!clientFilter||scoped.applications.some(a=>a.candidate_id===c.id&&entityFor(scoped.searches.find(s=>s.id===a.search_id)?.unit_id||'')?.client_id===clientFilter))).map(c=>[<div className="person-cell"><Avatar name={c.name}/><button className="row-link" onClick={()=>setModal({type:'candidate-detail',record:c})}>{c.name}</button></div>,<>{c.dni||'Sin DNI'}<small>{c.cuil||'Sin CUIL'}</small></>,c.location,c.email,scoped.applications.filter(a=>a.candidate_id===c.id).length,<button className="icon-btn" aria-label={'Ver ficha de '+c.name} onClick={()=>setModal({type:'candidate-detail',record:c})}><ChevronRight size={18}/></button>])}/></section>}
 {page==='Reportes'&&<><section className="panel report-filters"><label>Cliente<select value={clientFilter} onChange={e=>setClientFilter(e.target.value)}><option value="">Todos mis clientes</option>{scoped.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="secondary" onClick={()=>{setFrom('');setTo('');setClientFilter('')}}><RefreshCw size={16}/>Limpiar</button><button className="primary" onClick={()=>exportCsv(reportSearch.map(s=>({Puesto:s.title,Cliente:clientFor(s.unit_id),Unidad:unitName(s.unit_id),Vacantes:s.vacancies,Estado:s.status,Apertura:date(s.created_at)})))}><Download size={16}/>Exportar CSV</button></section><div className="metrics report-metrics">{[{label:'Requerimientos',value:reportReq.length},{label:'Vacantes solicitadas',value:vacancies},{label:'Candidatos',value:new Set(reportApp.map(a=>a.candidate_id)).size},{label:'Entrevistas',value:reportInterviews.length},{label:'Ingresos',value:covered},{label:'Cobertura',value:(vacancies?Math.round(covered/vacancies*100):0)+'%'}].map(m=><div className="metric" key={m.label}><span>{m.label}</span><strong>{m.value}</strong></div>)}</div><section className="panel"><div className="panel-heading"><div><h2>Resultados por cliente</h2><p>Cobertura y actividad del período seleccionado</p></div><span>Tiempo promedio: {average} días</span></div><GenericTable headers={['CLIENTE','REQUERIMIENTOS','VACANTES','INGRESOS','COBERTURA']} rows={scoped.clients.filter(c=>!clientFilter||c.id===clientFilter).map(c=>{const r=reportReq.filter(r=>r.client_id===c.id);const v=r.reduce((n,r)=>n+r.vacancies,0);const a=reportApp.filter(a=>a.stage==='Ingresado'&&reportSearch.some(s=>s.id===a.search_id&&entityFor(s.unit_id)?.client_id===c.id)).length;return [c.name,r.length,v,a,<span className="coverage-value">{v?Math.round(a/v*100):0}%</span>]})}/></section></>}
 {page==='Actividad'&&<section className="panel">{toolbar()}<ActivityList data={{...scoped,activity:scoped.activity.filter(a=>match(a.action))}}/></section>}
 {page==='Configuración'&&<div className="settings-grid"><section className="panel settings-card"><ShieldCheck size={28}/><h2>Conexión y seguridad</h2><Badge>{demo?'Demostración':'Supabase conectado'}</Badge><p>{demo?'Esta vista utiliza información ficticia. La base real se activa al configurar las variables de entorno y ejecutar las migraciones incluidas.':'La información se consulta con tu sesión de Supabase y los permisos de la base.'}</p><dl><dt>Registro público</dt><dd>Deshabilitado en la interfaz</dd><dt>Permisos</dt><dd>Cliente + unidades asignadas</dd><dt>Integración ARCA</dt><dd>Preparada para futura integración autorizada</dd><dt>Emails de negocio</dt><dd>Cola preparada · proveedor pendiente</dd></dl><small>Deshabilitá también el registro público en Supabase Auth antes de usar datos reales.</small></section><section className="panel settings-card"><Settings size={28}/><h2>Tu espacio NEXO</h2><p>El historial de procesos se conserva por candidato, sin duplicar su ficha personal.</p><dl><dt>Versión</dt><dd>MVP 0.1</dd><dt>Identidad</dt><dd>NEXO · Portal de Selección</dd><dt>Usuario</dt><dd>{user.name}</dd><dt>Rol</dt><dd>{roleNames[user.role]}</dd></dl>{demo&&<button className="secondary" onClick={()=>{sessionStorage.removeItem('nexo-demo');const d=makeDemo();setData(d);setUser(d.profiles[0]);setMessage('Demostración restablecida.')}}>Restablecer datos ficticios</button>}<button className="secondary" onClick={()=>setModal({type:'profile',record:user})}>Mi perfil</button></section></div>}
 </main><footer className="app-footer"><span>NEXO · Conectamos talento con oportunidades.</span><span>Portal de Selección <i/> MVP 0.1</span></footer></div>
 {message&&<div className="toast" role="status"><CheckCircle2 size={18}/>{message}</div>}
 {modal&&<ModalShell title={modalTitle(modal.type)} onClose={()=>{if(!busy){setModal(null);setError('')}}}>{error&&<div className="error" role="alert">{error}</div>}{modalContent()}</ModalShell>}
 </div>;

 function modalContent():ReactNode {
 const type=modal!.type,record=modal!.record;
 const entityFields:Field[]=[{key:'entity_id',label:'Razón social',options:options(scoped.entities),required:true}];
 const priorityField:Field={key:'priority',label:'Prioridad',options:['Baja','Media','Alta'].map(x=>({value:x,label:x})),required:true};
 const unitFields:Field[]=[...entityFields,{key:'name',label:'Nombre de la unidad',required:true},{key:'location',label:'Ubicación',required:true},{key:'responsible',label:'Responsable',required:true},{key:'notes',label:'Observaciones',type:'textarea',wide:true}];
 if(type==='client')return <Form busy={busy} fields={[{key:'name',label:'Nombre comercial',required:true},{key:'entity_name',label:'Razón social inicial',required:true},{key:'cuit',label:'CUIT'},{key:'contact',label:'Contacto'},{key:'email',label:'Email',type:'email'},{key:'phone',label:'Teléfono'},{key:'notes',label:'Observaciones',type:'textarea',wide:true}]} onSubmit={v=>run(async()=>{const id=uid();if(demo)await mutate(d=>{d.clients.push({id,name:v.name,contact:v.contact,email:v.email,phone:v.phone,status:'Activo',notes:v.notes});d.entities.push({id:uid(),client_id:id,name:v.entity_name,cuit:v.cuit});logDemo(d,user!,'Creó el cliente '+v.name,id)});else{await rpc('create_client',{p_name:v.name,p_entity_name:v.entity_name,p_cuit:v.cuit,p_contact:v.contact,p_email:v.email,p_phone:v.phone,p_notes:v.notes});await refresh()}})}/>;
 if(type==='entity')return <Form busy={busy} fields={[{key:'client_id',label:'Cliente',options:options(scoped.clients),required:true},{key:'name',label:'Razón social',required:true},{key:'cuit',label:'CUIT'}]} onSubmit={v=>run(()=>save('entities',{id:uid(),...v},'Creó una razón social'))}/>;
 if(type==='unit'||type==='request-unit')return <Form busy={busy} fields={unitFields} submitLabel={type==='unit'?'Crear unidad':'Enviar solicitud'} onSubmit={v=>run(async()=>{const entity=scoped.entities.find(e=>e.id===v.entity_id)!;if(type==='unit')await save('units',{id:uid(),entity_id:v.entity_id,name:v.name,location:v.location,responsible:v.responsible},'Creó una unidad');else await submitRequest('unidad',entity.client_id,entity.id,null,'Media',v)},type==='unit'?'Unidad creada.':'Tu solicitud fue enviada correctamente.')}/>;
 if(type==='requirement')return <Form busy={busy} fields={[{key:'unit_id',label:'Unidad · razón social · cliente',options:scoped.units.map(u=>({value:u.id,label:`${u.name} · ${entityFor(u.id)?.name} · ${clientFor(u.id)}`})),required:true,wide:true},{key:'title',label:'Puesto',required:true},{key:'area',label:'Área',required:true},{key:'vacancies',label:'Cantidad de vacantes',type:'number',min:1,required:true},{key:'required_date',label:'Fecha requerida',type:'date',required:true},priorityField,{key:'modality',label:'Modalidad',options:['Presencial','Híbrida','Remota'].map(x=>({value:x,label:x})),required:true},{key:'schedule',label:'Jornada'},{key:'hours',label:'Horario'},{key:'location',label:'Lugar de trabajo'},{key:'experience',label:'Experiencia'},{key:'education',label:'Educación'},{key:'skills',label:'Competencias'},{key:'mandatory',label:'Requisitos excluyentes',type:'textarea'},{key:'desired',label:'Requisitos deseables',type:'textarea'},{key:'description',label:'Descripción del puesto',type:'textarea',required:true,wide:true},{key:'notes',label:'Observaciones',type:'textarea',wide:true}]} initialValues={{vacancies:1,priority:'Media',modality:'Presencial'}} submitLabel="Enviar requerimiento" onSubmit={v=>run(async()=>{const e=entityFor(v.unit_id)!;const {unit_id,title,vacancies,priority,required_date,...details}=v;await submitRequest('requerimiento',e.client_id,e.id,unit_id,priority,{title,vacancies:Number(vacancies),required_date,details})},'Requerimiento enviado para aprobación.')}/>;
 if(type==='request-user')return <Form busy={busy} fields={[...entityFields,{key:'name',label:'Nombre y apellido',required:true},{key:'email',label:'Email corporativo',type:'email',required:true},{key:'position',label:'Cargo'},{key:'phone',label:'Teléfono'},{key:'unit_id',label:'Unidad inicial',options:options(scoped.units),required:true},{key:'role',label:'Rol solicitado',options:['admin_cliente','gerente','lider'].map(r=>({value:r,label:roleNames[r as keyof typeof roleNames]})),required:true}]} submitLabel="Solicitar acceso" onSubmit={v=>run(async()=>{const e=scoped.entities.find(e=>e.id===v.entity_id)!;if(scoped.units.find(u=>u.id===v.unit_id)?.entity_id!==e.id)throw new Error('La unidad debe pertenecer a la razón social seleccionada.');await submitRequest('usuario',e.client_id,e.id,v.unit_id,'Media',{...v,unit_ids:[v.unit_id]})},'Solicitud de usuario enviada. Nunca se envían contraseñas por email.')}/>;
 if(type==='review')return <Review r={record} admin={!!admin} busy={busy} client={clientName(record.client_id)} onReview={(yes,reason)=>run(()=>approve(record,yes,reason),yes?'Solicitud aprobada.':'Solicitud rechazada.')}/>;
 if(type==='candidate')return <CandidateForm busy={busy} candidates={scoped.candidates} searches={scoped.searches} searchId={record?.search_id} onSave={(v,existing)=>run(async()=>{const {search_id,...values}=v;if(values.dni&&!/^[0-9]{7,8}$/.test(values.dni))throw new Error('El DNI debe tener 7 u 8 dígitos.');if(values.cuil&&!/^[0-9]{11}$/.test(values.cuil))throw new Error('El CUIL debe tener 11 dígitos.');let candidateId=existing?.id||uid();if(existing&&!search_id)throw new Error('Elegí una búsqueda para asociar al candidato existente.');if(demo)await mutate(d=>{if(!existing)d.candidates.push({id:candidateId,...values,dni:values.dni||null,cuil:values.cuil||null,birth_date:values.birth_date||null} as Candidate);if(search_id){if(d.applications.some(a=>a.search_id===search_id&&a.candidate_id===candidateId))throw new Error('El candidato ya participa de esta búsqueda.');const app={id:uid(),search_id,candidate_id:candidateId,stage:'Postulado',created_at:now()};d.applications.push(app);d.history.push({id:uid(),application_id:app.id,actor_id:user!.id,old_stage:null,new_stage:'Postulado',note:'Asociado a la búsqueda',created_at:now()});}logDemo(d,user!,existing?'Asoció un candidato existente':'Creó una ficha de candidato',candidateId)});else{candidateId=await rpc('save_candidate',{p_values:values,p_search_id:search_id||null,p_existing_id:existing?.id||null});await refresh()}},existing?'Candidato asociado.':'Candidato registrado.')}/>;
 if(type==='candidate-detail'){const c=scoped.candidates.find(x=>x.id===record.id)!;const apps=scoped.applications.filter(a=>a.candidate_id===c.id);return <><div className="candidate-hero"><Avatar name={c.name}/><div><h2>{c.name}</h2><p>{c.location} · {age(c.birth_date)!==null?`${age(c.birth_date)} años · ${age(c.birth_date)!>=18?'Mayor de edad':'Menor de edad'}`:'Edad sin informar'}</p></div></div><div className="detail-grid"><dl><dt>DNI / CUIL</dt><dd>{c.dni||'—'} / {c.cuil||'—'}</dd><dt>Fecha de nacimiento</dt><dd>{c.birth_date?date(c.birth_date+'T12:00:00'):'—'}</dd><dt>Email</dt><dd>{c.email||'—'}</dd><dt>Teléfono</dt><dd>{c.phone||'—'}</dd></dl><dl><dt>Experiencia</dt><dd>{c.experience||'—'}</dd><dt>Educación</dt><dd>{c.education||'—'}</dd><dt>Disponibilidad</dt><dd>{c.availability||'—'}</dd><dt>Pretensión salarial</dt><dd>{c.salary||'—'}</dd></dl></div>{c.notes&&<p className="detail-note">{c.notes}</p>}<div className="candidate-stat-row">{[['Procesos',apps.length],['Ingresos',apps.filter(a=>a.stage==='Ingresado').length],['No presentaciones',new Set(scoped.history.filter(h=>apps.some(a=>a.id===h.application_id)&&h.new_stage==='No se presentó').map(h=>h.application_id)).size],['Desistimientos',new Set(scoped.history.filter(h=>apps.some(a=>a.id===h.application_id)&&h.new_stage==='Desistió').map(h=>h.application_id)).size]].map(([label,n])=><div key={label}><strong>{n}</strong><small>{label}</small></div>)}</div><h3>Historial de selección</h3>{scoped.history.filter(h=>apps.some(a=>a.id===h.application_id)).sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(h=>{const a=apps.find(a=>a.id===h.application_id)!,s=scoped.searches.find(s=>s.id===a.search_id)!;return <div className="timeline-row" key={h.id}><i/><div><strong>{s.title} · {clientFor(s.unit_id)}</strong><p><Badge>{h.new_stage}</Badge> {h.old_stage&&<small>Desde: {h.old_stage}</small>}</p><p>{h.note}</p><small>{datetime(h.created_at)} · {data.profiles.find(p=>p.id===h.actor_id)?.name||h.actor_name||'Usuario autorizado'}</small></div></div>})}{!apps.length&&<Empty text="Esta persona todavía no participa de una búsqueda."/>}<h3>Entrevistas</h3>{scoped.interviews.filter(i=>apps.some(a=>a.id===i.application_id)).map(i=><div className="interview-card" key={i.id}><strong>{i.type} · {datetime(i.date)}</strong><Badge>{i.result}</Badge><p>{i.interviewer} · {i.recommendation}</p><p>Fortalezas: {i.strengths||'—'}</p><p>A mejorar: {i.weaknesses||'—'}</p><small>{i.notes}</small></div>)}</>}
 if(type==='move')return <Form busy={busy} fields={[{key:'stage',label:'Nuevo estado',options:[...stages,...outcomes].map(s=>({value:s,label:s})),required:true},{key:'note',label:'Observación / motivo',type:'textarea',required:true,wide:true}]} initialValues={{stage:record.stage}} submitLabel="Registrar movimiento" onSubmit={v=>run(()=>move(record.id,v.stage,v.note),'Movimiento registrado en el historial.')}/>;
 if(type==='interview')return <Form busy={busy} fields={[{key:'date',label:'Fecha y hora',type:'datetime-local',required:true},{key:'interviewer',label:'Entrevistador',required:true},{key:'type',label:'Tipo',options:['Selectora','Gerencial'].map(x=>({value:x,label:x})),required:true},{key:'result',label:'Resultado',options:['Realizada','Pendiente','No se presentó','Cancelada'].map(x=>({value:x,label:x})),required:true},{key:'recommendation',label:'Recomendación',options:['Recomendar','Recomendar con observaciones','No recomendar','Pendiente'].map(x=>({value:x,label:x})),required:true},{key:'strengths',label:'Fortalezas',type:'textarea'},{key:'weaknesses',label:'Debilidades',type:'textarea'},{key:'notes',label:'Observaciones',type:'textarea',wide:true}]} initialValues={{interviewer:user!.name,type:'Selectora',result:'Realizada',recommendation:'Pendiente'}} onSubmit={v=>run(()=>save('interviews',{id:uid(),application_id:record.id,...v,date:new Date(v.date).toISOString()},'Registró una entrevista',scoped.searches.find(s=>s.id===record.search_id)?.unit_id))}/>;
 if(type==='search-edit')return <Form busy={busy} fields={[{key:'interview_goal',label:'Objetivo de entrevistas',type:'number',min:1,required:true},{key:'status',label:'Estado de la búsqueda',options:['En búsqueda','Esperando feedback','Cubierta','Cancelada'].map(x=>({value:x,label:x})),required:true}]} initialValues={record} onSubmit={v=>run(async()=>{if(v.status==='Cubierta'&&scoped.applications.filter(a=>a.search_id===record.id&&a.stage==='Ingresado').length<record.vacancies)throw new Error('Confirmá todos los ingresos antes de marcar la búsqueda como cubierta.');if(demo)await mutate(d=>{const s=d.searches.find(s=>s.id===record.id)!;s.interview_goal=Number(v.interview_goal);s.status=v.status;s.closed_at=['Cubierta','Cancelada'].includes(v.status)?now():null;logDemo(d,user!,'Actualizó la búsqueda '+s.title,s.id,s.unit_id)});else{await rpc('update_search',{p_search_id:record.id,p_goal:Number(v.interview_goal),p_status:v.status});await refresh()}})}/>;
 if(type==='permissions')return <Permissions profile={record} data={scoped} busy={busy} onSave={(role,units,active)=>run(async()=>{if(record.id===user!.id&&(role!=='super_admin'||!active))throw new Error('No podés quitar tu propio acceso de administradora.');if(demo)await mutate(d=>{const p=d.profiles.find(p=>p.id===record.id)!;p.role=role as any;p.active=active;d.assignments=d.assignments.filter(a=>a.user_id!==p.id);d.assignments.push(...units.map(unit_id=>({user_id:p.id,unit_id})));logDemo(d,user!,'Actualizó los permisos de '+p.name,p.id)});else{await rpc('set_user_permissions',{p_user_id:record.id,p_role:role,p_unit_ids:units,p_active:active});await refresh()}})}/>;
 if(type==='client-detail')return <><dl><dt>Cliente</dt><dd>{record.name}</dd><dt>Contacto</dt><dd>{record.contact||'—'}</dd><dt>Email</dt><dd>{record.email||'—'}</dd><dt>Teléfono</dt><dd>{record.phone||'—'}</dd><dt>Observaciones</dt><dd>{record.notes||'—'}</dd></dl><h3>Razones sociales y unidades</h3>{scoped.entities.filter(e=>e.client_id===record.id).map(e=><div className="entity-detail" key={e.id}><strong>{e.name}</strong><small>CUIT: {e.cuit||'—'}</small>{scoped.units.filter(u=>u.entity_id===e.id).map(u=><p key={u.id}><MapPin size={14}/>{u.name} · {u.location}</p>)}</div>)}</>;
 if(type==='profile')return <dl><dt>Nombre</dt><dd>{record.name}</dd><dt>Email</dt><dd>{record.email}</dd><dt>Rol</dt><dd>{roleNames[record.role as keyof typeof roleNames]}</dd><dt>Cargo</dt><dd>{record.position||'—'}</dd><dt>Teléfono</dt><dd>{record.phone||'—'}</dd></dl>;
 return null;
 }
 async function submitRequest(type:Request['type'],client:string,entity:string,unit:string|null,priority:string,payload:any){const row:Request={id:uid(),client_id:client,entity_id:entity,unit_id:unit,requester_id:user!.id,type,status:'Pendiente',priority,payload,created_at:now()};if(demo)await mutate(d=>{d.requests.unshift(row);for(const p of d.profiles.filter(p=>p.role==='super_admin'))d.notifications.unshift({id:uid(),user_id:p.id,title:'Nueva solicitud de '+type,body:payload.name||payload.title,read:false,created_at:now(),request_id:row.id});logDemo(d,user!,'Envió una solicitud de '+type,row.id,unit)});else{await rpc('submit_request',{p_type:type,p_client_id:client,p_entity_id:entity,p_unit_id:unit,p_priority:priority,p_payload:payload});await refresh()}}
}

function GenericTable({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="table-wrap"><table><thead><tr>{headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty/>}</div>}
function ActivityList({data,limit=100}:{data:Data;limit?:number}){return <div className="activity-list">{data.activity.slice().sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,limit).map(a=><div className="activity-row" key={a.id}><span className="activity-icon"><Activity size={16}/></span><div><strong>{a.action}</strong><small>{data.profiles.find(p=>p.id===a.actor_id)?.name||a.actor_name||'Usuario autorizado'} · {datetime(a.created_at)}</small></div></div>)}{!data.activity.length&&<Empty text="La actividad de tu equipo aparecerá acá."/>}</div>}
function Review({r,admin,busy,client,onReview}:{r:Request;admin:boolean;busy:boolean;client:string;onReview:(approve:boolean,reason:string)=>void}){const [reason,setReason]=useState('');return <><div className="review-heading"><Badge>{r.status}</Badge><Badge>{r.priority}</Badge></div><dl><dt>Cliente</dt><dd>{client}</dd><dt>Fecha</dt><dd>{datetime(r.created_at)}</dd>{Object.entries(r.payload).filter(([k])=>!['entity_id','unit_ids','unit_id'].includes(k)).map(([k,v])=><div key={k}><dt>{({name:'Nombre',title:'Puesto',email:'Email',role:'Rol',position:'Cargo',phone:'Teléfono',location:'Ubicación',responsible:'Responsable',notes:'Observaciones',vacancies:'Vacantes',required_date:'Fecha requerida',details:'Detalles'} as any)[k]||k}</dt><dd>{typeof v==='object'?Object.entries(v).map(([dk,dv])=><p key={dk}>{detailLabels[dk]||dk}: {String(dv)||'—'}</p>):String(v)}</dd></div>)}{r.reason&&<><dt>Motivo</dt><dd>{r.reason}</dd></>}{r.reviewed_at&&<><dt>Revisada</dt><dd>{datetime(r.reviewed_at)}</dd></>}</dl>{admin&&r.status==='Pendiente'&&<><label>Observaciones / motivo de rechazo<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="El motivo es obligatorio para rechazar."/></label><div className="review-actions"><button className="danger" disabled={busy||!reason.trim()} onClick={()=>onReview(false,reason)}>Rechazar</button><button className="primary" disabled={busy} onClick={()=>onReview(true,reason)}><Check size={16}/>{busy?'Procesando…':'Aprobar solicitud'}</button></div></>}</>}
const detailLabels:Record<string,string>={area:'Área',modality:'Modalidad',schedule:'Jornada',hours:'Horario',location:'Lugar de trabajo',experience:'Experiencia',education:'Educación',skills:'Competencias',mandatory:'Requisitos excluyentes',desired:'Requisitos deseables',description:'Descripción',notes:'Observaciones'};
function Permissions({profile,data,busy,onSave}:{profile:Profile;data:Data;busy:boolean;onSave:(r:string,ids:string[],active:boolean)=>void}){const [role,setRole]=useState(profile.role);const [units,setUnits]=useState(data.assignments.filter(a=>a.user_id===profile.id).map(a=>a.unit_id));const [active,setActive]=useState(profile.active);return <><h3>{profile.name}</h3><p>{profile.email}</p><label>Rol<select value={role} onChange={e=>setRole(e.target.value as any)}>{Object.entries(roleNames).filter(([r])=>profile.client_id?r!=='super_admin':r==='super_admin').map(([r,n])=><option key={r} value={r}>{n}</option>)}</select></label><label className="checkbox-label"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Acceso activo</label><h3>Unidades asignadas</h3>{data.units.filter(u=>data.entities.find(e=>e.id===u.entity_id)?.client_id===profile.client_id).map(u=><label className="checkbox-label" key={u.id}><input type="checkbox" checked={units.includes(u.id)} onChange={e=>setUnits(e.target.checked?[...units,u.id]:units.filter(id=>id!==u.id))}/>{u.name}<small>{data.entities.find(e=>e.id===u.entity_id)?.name}</small></label>)}{!profile.client_id&&<p>La administradora accede a todos los clientes y unidades.</p>}<div className="form-footer"><button className="primary" disabled={busy} onClick={()=>onSave(role,units,active)}>Guardar permisos</button></div></>}
function CandidateForm({candidates,searches,searchId,busy,onSave}:{candidates:Candidate[];searches:Search[];searchId?:string;busy:boolean;onSave:(v:any,existing:Candidate|null)=>void}){const [duplicate,setDuplicate]=useState<{values:any;c:Candidate}|null>(null);return duplicate?<div className="duplicate"><Users size={30}/><h3>Candidato existente</h3><p>{duplicate.c.name} ya está registrado en NEXO. ¿Querés asociarlo a esta búsqueda?</p><div className="review-actions"><button className="secondary" onClick={()=>setDuplicate(null)}>Cancelar</button><button className="primary" disabled={busy} onClick={()=>onSave(duplicate.values,duplicate.c)}>Asociar</button></div></div>:<Form busy={busy} fields={[{key:'name',label:'Nombre completo',required:true},{key:'dni',label:'DNI'},{key:'cuil',label:'CUIL'},{key:'birth_date',label:'Fecha de nacimiento',type:'date',max:now().slice(0,10)},{key:'email',label:'Email',type:'email'},{key:'phone',label:'Teléfono'},{key:'location',label:'Localidad'},{key:'education',label:'Educación'},{key:'experience',label:'Experiencia / puestos anteriores',type:'textarea'},{key:'availability',label:'Disponibilidad'},{key:'salary',label:'Pretensión salarial'},{key:'search_id',label:'Asociar a búsqueda',options:options(searches.filter(s=>!['Cubierta','Cancelada'].includes(s.status)),'title')},{key:'notes',label:'Observaciones',type:'textarea',wide:true}]} initialValues={{search_id:searchId}} onSubmit={async v=>{const normalized={...v,dni:v.dni.replace(/\D/g,''),cuil:v.cuil.replace(/\D/g,'')};const existing=candidates.find(c=>(normalized.dni&&c.dni===normalized.dni)||(normalized.cuil&&c.cuil===normalized.cuil));if(existing)setDuplicate({values:normalized,c:existing});else onSave(normalized,null)}}/>}
function SearchDetail({search:s,data,admin,unit,client,back,onCandidate,onAdd,onMove,onInterview,onEdit}:{search:Search;data:Data;admin:boolean;unit:string;client:string;back:()=>void;onCandidate:(c:Candidate)=>void;onAdd:()=>void;onMove:(a:any)=>void;onInterview:(a:any)=>void;onEdit:()=>void}){const [view,setView]=useState('Pipeline');const apps=data.applications.filter(a=>a.search_id===s.id);const interviews=data.interviews.filter(i=>i.result==='Realizada'&&apps.some(a=>a.id===i.application_id)).length;const r=data.requirements.find(r=>r.id===s.requirement_id);return <><button className="text-btn back-btn" onClick={back}>Volver a búsquedas</button><section className="panel search-detail-heading"><div><span className="eyebrow">NX-{s.id.slice(-5)}</span><h2>{s.title}</h2><p>{client} · {unit}</p><Badge>{s.status}</Badge></div><div className="search-numbers"><div><strong>{s.vacancies}</strong><small>Vacantes</small></div><div><strong>{interviews}<span> / {s.interview_goal}</span></strong><small>{interviews>=s.interview_goal?'Objetivo alcanzado':'Objetivo de entrevistas'}</small></div></div>{admin&&<button className="secondary" onClick={onEdit}><Settings size={16}/>Configurar</button>}</section><div className="section-tabs"><div>{['Pipeline','Requerimiento'].map(v=><button key={v} className={v===view?'selected':''} onClick={()=>setView(v)}>{v}</button>)}</div>{admin&&<button className="primary" onClick={onAdd}><Plus size={16}/>Agregar candidato</button>}</div>{view==='Requerimiento'?<section className="panel requirement-detail"><h3>Perfil solicitado</h3><dl><dt>Fecha requerida</dt><dd>{r?.required_date?date(r.required_date+'T12:00:00'):'—'}</dd><dt>Prioridad</dt><dd>{r?.priority}</dd>{Object.entries(r?.details||{}).filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{detailLabels[k]||k}</dt><dd>{v}</dd></div>)}</dl></section>:<><div className="pipeline-board">{[...stages,...outcomes.filter(o=>apps.some(a=>a.stage===o))].map(stage=><section className="pipeline-column" key={stage}><header><span>{stage}</span><b>{apps.filter(a=>a.stage===stage).length}</b></header><div>{apps.filter(a=>a.stage===stage).map(a=>{const c=data.candidates.find(c=>c.id===a.candidate_id)!;return <article className="candidate-card" key={a.id}><button className="candidate-card-name" onClick={()=>onCandidate(c)}><Avatar name={c.name}/><strong>{c.name}</strong></button><p><MapPin size={13}/>{c.location||'Sin localidad'}</p><small>DNI {c.dni||'sin informar'}</small>{admin&&<div className="candidate-actions"><button onClick={()=>onMove(a)}>Cambiar etapa</button><button onClick={()=>onInterview(a)} aria-label={'Registrar entrevista de '+c.name}><CalendarDays size={16}/></button></div>}</article>})}{!apps.some(a=>a.stage===stage)&&<span className="column-empty">Sin candidatos</span>}</div></section>)}</div><p className="pipeline-help"><ShieldCheck size={15}/>Cada cambio de etapa registra la fecha, el usuario y el motivo.</p></>}</>}
function modalTitle(type:string){return ({client:'Nuevo cliente',entity:'Nueva razón social',unit:'Nueva unidad de negocio','request-unit':'Solicitar nueva unidad',requirement:'Nuevo requerimiento','request-user':'Solicitar alta de usuario',review:'Detalle de solicitud',candidate:'Registrar candidato','candidate-detail':'Ficha del candidato',move:'Cambiar etapa',interview:'Registrar entrevista','search-edit':'Configurar búsqueda',permissions:'Permisos del usuario','client-detail':'Detalle del cliente',profile:'Perfil'} as Record<string,string>)[type]||'NEXO'}
function exportCsv(rows:Record<string,any>[]){if(!rows.length)return;const escape=(v:any)=>{let str=String(v??'');if(/^[=+\-@\t\r]/.test(str))str="'"+str;return '"'+str.replaceAll('"','""')+'"'};const keys=Object.keys(rows[0]);const csv='\uFEFF'+[keys.map(escape).join(';'),...rows.map(r=>keys.map(k=>escape(r[k])).join(';'))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='nexo-reportes.csv';a.click();URL.revokeObjectURL(url)}
