import {Data,stages} from './model';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
export function makeDemo():Data {
 const date=(offset:number)=>new Date(Date.now()-offset*86400000).toISOString();
 const names=['Grupo Andina','Tolosa Demo','Nova Logística','Faro Retail','Atlas Industrial'];
 const clients=names.map((name,i)=>({id:id(i+1),name,contact:['Marina Soto','Diego Ríos','Lucía Vera','Pablo Mora','Ana Vidal'][i],email:`contacto${i+1}@example.com`,phone:'',status:'Activo',notes:'Empresa ficticia de demostración'}));
 const entities=Array.from({length:8},(_,i)=>({id:id(100+i),client_id:clients[i%5].id,name:`${names[i%5]} ${i<5?'Argentina S.A.':'Servicios S.R.L.'}`,cuit:`30-${String(10000000+i)}-0`}));
 const units=Array.from({length:15},(_,i)=>({id:id(200+i),entity_id:entities[i%8].id,name:['Planta Buenos Aires','Administración','Centro de distribución','Planta Córdoba','Operaciones'][i%5]+(i>7?' · Sur':''),location:['Buenos Aires','Córdoba','Rosario'][i%3],responsible:'Responsable de demostración'}));
 const profiles=Array.from({length:20},(_,i)=>({id:id(300+i),name:i===0?'Micaela Demo':['Juan Pérez Demo','Laura Gómez Demo','Martín Silva Demo','Carolina Díaz Demo'][((i-1)%4)]+' '+(i>4?i:''),email:`usuario${i}@example.com`,role:(i===0?'super_admin':i%3===0?'admin_cliente':i%3===1?'gerente':'lider') as any,client_id:i===0?null:clients[(i-1)%5].id,active:true,position:i===0?'Selectora':'Responsable de área',phone:''}));
 const assignments=profiles.slice(1).flatMap(p=>units.filter(u=>entities.find(e=>e.id===u.entity_id)?.client_id===p.client_id).map(u=>({user_id:p.id,unit_id:u.id})));
 const titles=['Operario de producción','Analista de administración','Supervisor de logística','Ejecutivo comercial','Técnico de mantenimiento','Asistente de RR. HH.','Coordinador de operaciones'];
 const requirements=Array.from({length:20},(_,i)=>{const u=units[i%15],e=entities.find(e=>e.id===u.entity_id)!;return {id:id(400+i),client_id:e.client_id,entity_id:e.id,unit_id:u.id,requester_id:profiles.find(p=>p.client_id===e.client_id)!.id,title:titles[i%7],vacancies:i%4+1,priority:i%5===0?'Alta':'Media',status:'Aprobado',required_date:date(-8).slice(0,10),details:{area:'Operaciones',modality:'Presencial',schedule:'Jornada completa',description:'Experiencia en el puesto, capacidad de trabajo en equipo y compromiso.'},created_at:date(i+1)};});
 const searches=requirements.map((r,i)=>({id:id(500+i),requirement_id:r.id,unit_id:r.unit_id,title:r.title,vacancies:r.vacancies,interview_goal:r.vacancies*3,status:i>=16?'Cubierta':i%4===0?'Esperando feedback':'En búsqueda',created_at:r.created_at,closed_at:i>=16?date(1):null}));
 const given=['Sofía','Mateo','Valentina','Nicolás','Camila','Tomás','Luciana','Santiago','Julieta','Facundo'];
 const surnames=['Acosta','Benítez','Castro','Domínguez','Ferrer','Giménez','Herrera','Ibarra','Luna','Molina'];
 const candidates=Array.from({length:100},(_,i)=>({id:id(600+i),name:`${given[i%10]} ${surnames[Math.floor(i/10)]} (Demo)`,dni:String(90000000+i),cuil:null,birth_date:`${1988+i%14}-04-12`,email:`candidato${i+1}@example.com`,phone:'',location:['San Miguel','José C. Paz','Buenos Aires','Córdoba'][i%4],experience:'Experiencia ficticia de 3 años en el área.',education:'Secundario completo',availability:'Inmediata',salary:'A convenir',notes:'Datos completamente ficticios.'}));
 const applications=candidates.map((c,i)=>({id:id(800+i),candidate_id:c.id,search_id:searches[i%20].id,stage:i%20>=16?(Math.floor(i/20)<searches[i%20].vacancies?'Ingresado':'No seleccionado'):stages[i%7],created_at:date(i%15+1)}));
 const interviews=applications.filter((a,i)=>i%3===0).map((a,i)=>({id:id(1000+i),application_id:a.id,date:date(i%8).slice(0,16),interviewer:'Micaela Demo',type:'Selectora',result:'Realizada',strengths:'Experiencia y comunicación',weaknesses:'A profundizar en próxima entrevista',notes:'Entrevista ficticia de demostración',recommendation:'Recomendar'}));
 const history=applications.map((a,i)=>({id:id(1200+i),application_id:a.id,actor_id:profiles[0].id,old_stage:null,new_stage:a.stage,note:'Proceso de demostración',created_at:date(i%15)}));
 const requests=Array.from({length:7},(_,i)=>{const r=requirements[i],type=(i%3===0?'unidad':i%3===1?'requerimiento':'usuario') as any;return {id:id(1400+i),client_id:r.client_id,entity_id:r.entity_id,unit_id:r.unit_id,requester_id:r.requester_id,type,status:'Pendiente',priority:i%2?'Media':'Alta',payload:type==='unidad'?{name:'Nueva sede · '+(i+1),location:'Buenos Aires',responsible:'Juan Demo',notes:'Ampliación del equipo'}:type==='usuario'?{name:'Nuevo usuario Demo '+i,email:`nuevo${i}@example.com`,role:'gerente',position:'Gerente',phone:'',unit_ids:[r.unit_id]}:{title:'Auxiliar de operaciones',vacancies:2,required_date:date(-10).slice(0,10),details:{description:'Refuerzo para el equipo de operaciones'}},created_at:date(i%3)};});
 const activity=[{id:id(1500),actor_id:profiles[0].id,action:'Registró una entrevista para Operario de producción',record_id:interviews[0].id,unit_id:searches[0].unit_id,created_at:date(0)},{id:id(1501),actor_id:profiles[1].id,action:'Solicitó el alta de una nueva unidad',record_id:requests[0].id,unit_id:units[0].id,created_at:date(1)}];
 const notifications=requests.map((r,i)=>({id:id(1600+i),user_id:profiles[0].id,title:'Nueva solicitud',body:r.type==='unidad'?'Nueva unidad pendiente de aprobación':r.type==='usuario'?'Alta de usuario pendiente':'Nuevo requerimiento recibido',read:false,created_at:r.created_at,request_id:r.id}));
 return {clients,entities,units,profiles,assignments,requests,requirements,searches,candidates,applications,interviews,history,activity,notifications};
}
